const express = require("express")
const router = express.Router()
const { messageList, postMsg, startOrGetMsg } = require('../controllers/message/messagecontroller')
const { authenticatedUserDetails } = require("../controllers/authenticateduser")
const { createJob } = require('../controllers/createJob/createJob')
const { getpost } = require("../controllers/home/home")
const { jobapply } = require("../controllers/jobapply/jobapply")
const { removeDisLike, addDisLike, removelike, addlike } = require('../controllers/postmanage/likeDislike')
const { postComment } = require('../controllers/postmanage/comments')
const {getUserById}= require('../controllers/getuserByid')

router.get('/getUser/:id', getUserById)
router.get('/',)
router.get('/msg', messageList)
router.post('/msg', startOrGetMsg)
router.post('/msg/:chatId', postMsg)
router.get('/authenticated', authenticatedUserDetails)
router.post('/createJob/:authorId', createJob)
router.get('/home', getpost)
router.post('/jobapply', jobapply)
router.patch('/adddislike/:postId', addDisLike)
router.patch('/addlike/:postId', addlike)
router.delete('/removedislike/:postId', removeDisLike)
router.delete('/removelike/:postId', removelike)
router.post('/comment/:postId', postComment)

module.exports = router