const jobData = [
    { title: 'Software Engineer', company: 'TechCorp', location: 'San Francisco, CA' },
    { title: 'Web Developer', company: 'WebTech', location: 'New York, NY' },
    { title: 'Data Analyst', company: 'DataWorks', location: 'Chicago, IL' },
    { title: 'UX Designer', company: 'DesignHub', location: 'Los Angeles, CA' },
    { title: 'Network Administrator', company: 'NetSys', location: 'Seattle, WA' },
    { title: 'Mobile App Developer', company: 'AppTech', location: 'Austin, TX' },
    { title: 'Digital Marketing Specialist', company: 'Marketers Inc.', location: 'Boston, MA' },
    { title: 'Systems Analyst', company: 'SysTech', location: 'Denver, CO' },
    { title: 'Frontend Developer', company: 'FrontTech', location: 'Portland, OR' },
    { title: 'Backend Developer', company: 'BackTech', location: 'Miami, FL' },
    { title: 'Data Scientist', company: 'DataTech', location: 'San Jose, CA' },
    { title: 'UI Designer', company: 'UIUX Designs', location: 'Seattle, WA' },
    { title: 'Cloud Engineer', company: 'CloudTech', location: 'Austin, TX' },
    { title: 'Product Manager', company: 'Product Inc.', location: 'New York, NY' },
    { title: 'DevOps Engineer', company: 'DevOps Solutions', location: 'Chicago, IL' },
    { title: 'Business Analyst', company: 'BizWorks', location: 'Los Angeles, CA' },
    { title: 'Sales Manager', company: 'SalesForce', location: 'Denver, CO' },
    { title: 'AI Research Scientist', company: 'AI Innovations', location: 'San Francisco, CA' },
    { title: 'Machine Learning Engineer', company: 'ML Solutions', location: 'Seattle, WA' },
    { title: 'Cybersecurity Analyst', company: 'CyberDefend', location: 'New York, NY' },
    { title: 'Blockchain Developer', company: 'ChainTech', location: 'Miami, FL' },
    { title: 'AR/VR Developer', company: 'VirtualTech', location: 'Los Angeles, CA' },
    { title: 'Robotics Engineer', company: 'RoboTech', location: 'Boston, MA' },
    { title: 'Quantum Computing Scientist', company: 'QuantumTech', location: 'San Jose, CA' },
    { title: 'Bioinformatics Analyst', company: 'BioTech', location: 'Chicago, IL' },
    { title: 'Renewable Energy Engineer', company: 'EcoTech', location: 'Portland, OR' },
    { title: 'Healthcare IT Specialist', company: 'HealthTech', location: 'Denver, CO' },
    { title: 'Environmental Consultant', company: 'EnviroSolutions', location: 'San Francisco, CA' },
    { title: 'Financial Analyst', company: 'FinTech', location: 'New York, NY' },
    { title: 'Supply Chain Manager', company: 'SupplyTech', location: 'Seattle, WA' },
    { title: 'Marketing Director', company: 'MarketTech', location: 'Los Angeles, CA' },
    { title: 'Quality Assurance Engineer', company: 'QA Solutions', location: 'Chicago, IL' },
    { title: 'Cloud Security Specialist', company: 'SecureCloud', location: 'Austin, TX' },
    { title: 'Data Privacy Officer', company: 'DataPrivacy', location: 'Boston, MA' },
    { title: 'Medical Research Scientist', company: 'MedTech', location: 'San Francisco, CA' },
    { title: 'Telecommunications Engineer', company: 'TelecomTech', location: 'Denver, CO' },
    { title: 'Urban Planner', company: 'UrbanTech', location: 'Portland, OR' },
    { title: 'Game Developer', company: 'GameTech', location: 'Los Angeles, CA' },
    { title: 'Human Resources Manager', company: 'HR Solutions', location: 'New York, NY' },
    { title: 'Project Manager', company: 'Project Solutions', location: 'Seattle, WA' },
    { title: 'Legal Counsel', company: 'LegalTech', location: 'Chicago, IL' },
    { title: 'Customer Success Manager', company: 'CustomerSuccess', location: 'Austin, TX' },
    { title: 'Product Designer', company: 'ProductDesigns', location: 'San Francisco, CA' },
    { title: 'Operations Manager', company: 'Ops Solutions', location: 'san franciso, ca '}
]

module.exports={jobData}